server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/xtel_db
    username: postgres
    password: 1234
    initialize: true
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: xtel
  liquibase:
    enabled: true
    default-schema: xtel

logging:
  level:
    org:
      springframework:
        web: debug
        jdbc: debug
    root: info
  file:
    path: './var/log'
    name: ${logging.file.path}/xtel-web.log
  logback:
    rollingpolicy:
      total-size-cap: 200MB
